version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_ylab
      POSTGRES_PASSWORD: password_ylab
      POSTGRES_DB: habit_ylab_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
